project:
  type: website

website:
  title: "Circulo Editorial Científico Venezolano"
  favicon: favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: members.qmd
        text: Miembros actuales

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: source

